### ISSUE TITLE
Cannot read property 'identifier' of undefined -- regression in 2.1.1

### ISSUE THREAD

**Issue by niieani** [niieani/chunk-splitting-plugin#10]
Unfortunately, on a bigger project #9 is now causing a regression:

```
uncaughtException TypeError: Cannot read property 'identifier' of undefined
    at origins.sort (./node_modules/webpack/lib/Chunk.js:431:27)
    at Array.sort (native)
    at Array.sort (./node_modules/core-js/modules/es6.array.sort.js:21:15)
    at Chunk.sortItems (./node_modules/webpack/lib/Chunk.js:430:16)
    at Compilation.sortItemsWithModuleIds (./node_modules/webpack/lib/Compilation.js:1090:23)
    at sealPart2 (./node_modules/webpack/lib/Compilation.js:602:9)
    at next (./node_modules/tapable/lib/Tapable.js:138:11)
    at Compilation.compilation.plugin (./node_modules/webpack/lib/ProgressPlugin.js:111:6)
    at Compilation.applyPluginsAsyncSeries (./node_modules/tapable/lib/Tapable.js:142:13)
    at Compilation.seal (./node_modules/webpack/lib/Compilation.js:579:8)
    at applyPluginsParallel.err (./node_modules/webpack/lib/Compiler.js:514:17)
    at ./node_modules/tapable/lib/Tapable.js:225:11
    at _addModuleChain (./node_modules/webpack/lib/Compilation.js:481:11)
    at processModuleDependencies.err (./node_modules/webpack/lib/Compilation.js:452:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by niieani** [comment]
Releasing #11 until we understand what's going on.
