### ISSUE TITLE
Compatibility with webpack 4

### ISSUE THREAD

**Issue by SamyPesse** [niieani/chunk-splitting-plugin#30]
When trying to use this plugin with webpack v4, I'm getting the error:

```js
const async = !chunk.isInitial()
                         ^

TypeError: chunk.isInitial is not a function
    at chunk (/Users/samypesse/Projects/GitBook/gitbook-new/node_modules/chunk-splitting-plugin/ChunkSplittingPlugin.js:156:26)
    at arrayMap (/Users/samypesse/Projects/GitBook/gitbook-new/node_modules/lodash/lodash.js:660:23)
    at map (/Users/samypesse/Projects/GitBook/gitbook-new/node_modules/lodash/lodash.js:9571:14)
    at flatMap (/Users/samypesse/Projects/GitBook/gitbook-new/node_modules/lodash/lodash.js:9274:26)
    at breakChunksIntoPieces (/Users/samypesse/Projects/GitBook/gitbook-new/node_modules/chunk-splitting-plugin/ChunkSplittingPlugin.js:155:10)
```

**Comment by niieani** [comment]
Hi @SamyPesse. I am aware of the issue. I do not currently have time to migrate the plugin to Webpack 4. I'm open to PRs that do so, though.

Thanks for understanding.
